In [2]:
import numpy as np
a = np.array([[2, 3, 1, 7, 4], [3, 8, 6, 1, 3]], dtype ="int32")
print(a)

[[2 3 1 7 4]
 [3 8 6 1 3]]


In [27]:
#get dimension
a.ndim

2

In [28]:
#get shape
a.shape

(2, 5)

In [33]:
#get type
a.dtype



dtype('int16')

In [36]:
#
a.itemsize

4

In [37]:
#
a.size

10

In [38]:
#get specific element
a[1][3]

1

In [49]:
#specific row
b= np.array([[2.1, 1.4, 2.9, 5.9, 7, 3, 8, 1], [2.6, 5.9, 1.7, 3.5, 7, 3, 9, 0]])
b[0, :]

array([2.1, 1.4, 2.9, 5.9, 7. , 3. , 8. , 1. ])

In [50]:
#speciifc coloumn
b[0, 1:6:2]

array([1.4, 5.9, 3. ])

In [57]:
c = np.array([[2, 3, 4, 5, 6], [8, 7, 2, 1, 2], [5, 4, 6, 7, 8], [9, 3, 5, 1, 7]])
print(c)
#print(c[2:4, 2:])

[[2 3 4 5 6]
 [8 7 2 1 2]
 [5 4 6 7 8]
 [9 3 5 1 7]]


In [59]:
c[1,2]= 6
c

array([[2, 3, 4, 5, 6],
       [8, 7, 6, 1, 2],
       [5, 4, 6, 7, 8],
       [9, 3, 5, 1, 7]])

In [19]:
#3d array
k = np.array([[[2, 1, 3],
               [3, 1, 3]],
              [[2, 9, 0],
               [1, 6, 4]],
              [[6, 9, 5],
               [2, 6, 0]]])
k[1,1,1]

6

In [66]:
k[:2, 1, 1:] = [[13, 13],
                [13, 13]]
k

array([[[ 2,  1,  3],
        [ 3, 13, 13]],

       [[ 2,  9,  0],
        [ 1, 13, 13]],

       [[ 6,  9,  5],
        [ 2,  6,  0]]])

In [10]:
#all zeros matrix
np.zeros((2,4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
#all one matrix
np.ones((2, 3, 1), dtype = 'int64')

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int64)

In [16]:
np.full((2,3,6), 55, dtype = 'float32')

array([[[55., 55., 55., 55., 55., 55.],
        [55., 55., 55., 55., 55., 55.],
        [55., 55., 55., 55., 55., 55.]],

       [[55., 55., 55., 55., 55., 55.],
        [55., 55., 55., 55., 55., 55.],
        [55., 55., 55., 55., 55., 55.]]], dtype=float32)

In [20]:
#full_like function
np.full_like(k, 8)

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [26]:
#random decimal numbers
np.random.random((4,9))

array([[0.74647404, 0.15059178, 0.16075717, 0.10968474, 0.90361743,
        0.54050275, 0.96741724, 0.31144584, 0.39614057],
       [0.5386517 , 0.9319036 , 0.05558478, 0.49887789, 0.73755253,
        0.94876647, 0.81302434, 0.16487624, 0.4530041 ],
       [0.36314055, 0.08288819, 0.90309444, 0.64376648, 0.23955308,
        0.36666453, 0.71064856, 0.96663709, 0.47314714],
       [0.75334431, 0.23428825, 0.24648922, 0.06127018, 0.07878376,
        0.82199547, 0.7599474 , 0.57198811, 0.9732407 ]])

In [28]:
#random interger values
np.random.randint(-4,4, size=(4,2))

array([[-2,  0],
       [ 3, -1],
       [ 1, -4],
       [-3,  3]])

In [29]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
tarr = np.ones((5,5), dtype='int16')
tarr
tarrz = np.zeros((3,3), dtype='int16')
tarrz
tarrz[1,1]=9
tarrz
tarr[1:4, 1:4] = tarrz
tarr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [40]:
a = np.array([1, 3, 5])
b = a.copy()
b[1] = 7
b

array([1, 7, 5])

In [55]:
na = np.array([3, 6, 1, 0, 4, 2])
na +5
na * 2
np.sin(a)

array([ 0.84147098,  0.14112001, -0.95892427])

In [57]:
#matrix multiplication
m1 = np.full((3,5), 4)
m2 = np.full((5,2), 9)
np.matmul(m1, m2)

array([[180, 180],
       [180, 180],
       [180, 180]])

In [64]:
st = np.array([[2, 5, 9],
               [4, 2, 1],
               [0, 4, 1]])
np.min(st)
np.max(st)

9

In [66]:
#sum all values
np.sum(st, axis = 0)

array([ 6, 11, 11])

In [70]:
#reshape
st.shape
st1 = st.reshape((1,9))
st1

array([[2, 5, 9, 4, 2, 1, 0, 4, 1]])

In [73]:
#vertical stacking of one array on top of another
a1 = np.array([4, 3, 9, 1])
a2 = np.array([5, 8, 9, 1])
a3 = np.array([[6, 7, 2, 3],
             [3, 6, 1, 0]])
np.vstack([a1, a2, a3, a2, a3])

array([[4, 3, 9, 1],
       [5, 8, 9, 1],
       [6, 7, 2, 3],
       [3, 6, 1, 0],
       [5, 8, 9, 1],
       [6, 7, 2, 3],
       [3, 6, 1, 0]])

In [91]:
#loading data from a file
filedt= np.genfromtxt('C:\\Users\\Admin\\Desktop\\numpydt.txt', delimiter = ',')

filedt


array([[ 23.,  43.,   4.,   2.,  34., 646., 343., 446., 354.,  35.],
       [  5.,   3.,  45.,  43.,  53., 453.,  54., 354.,  36., 435.],
       [  4.,  35.,  43.,  43.,   5.,  43.,   5.,  34.,   3.,   4.],
       [  4.,  54.,  56., 442.,  42.,  54.,  36.,  56., 546.,  45.]])

In [87]:
#ADVANCED INDEXING AND BOOLEAN MASKING

filedt>50

array([[False, False, False, False, False,  True,  True,  True,  True,
        False],
       [False, False, False, False,  True,  True,  True,  True, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False,  True, False,  True,  True,
        False]])

In [94]:
filedt[filedt>50]


array([ 5., 53.])

In [96]:
## WE CAN INDEX WITH  LIST IN NUMPY
filedt[[1], [0, 4, 7]]

array([  5.,  53., 354.])

In [101]:
#print on conditions
print(filedt)
print((~(filedt>50) & (filedt<100)))

[[ 23.  43.   4.   2.  34. 646. 343. 446. 354.  35.]
 [  5.   3.  45.  43.  53. 453.  54. 354.  36. 435.]
 [  4.  35.  43.  43.   5.  43.   5.  34.   3.   4.]
 [  4.  54.  56. 442.  42.  54.  36.  56. 546.  45.]]
[[ True  True  True  True  True False False False False  True]
 [ True  True  True  True False False False False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False False False  True False  True False False  True]]
